package com.nlogneg.transcodingService.info.mediainfo;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

import com.nlogneg.transcodingService.utilities.Optional;
import com.nlogneg.transcodingService.utilities.SerializerFactory;
import com.thoughtworks.xstream.XStream;

/**
 * A deserialization utility class for XML generated by mediainfo
 * 
 * @author anjohnson
 * 
 */
public final class MediaInfoXmlDeserializer
{

	private static final Logger Log = LogManager.getLogger(MediaInfoXmlDeserializer.class);
	private static final XStream XStream = SerializerFactory.generateDefaultMediaInfoSerializer();

	/**
	 * Deserialize the XML coming from mediainfo
	 */
	public static Optional<MediaInfo> deserializeMediaInfo(final String xmlInput)
	{
		try
		{
			Log.info("Deserializing media info: " + xmlInput);

			final MediaInfo info = (MediaInfo) XStream.fromXML(xmlInput);
			return Optional.make(info);
		} catch (final Exception ex)
		{
			Log.error(
					"An error occurred while deserializing a MediaInfo object from XML.",
					ex);
		}

		return Optional.none();
	}

}
