//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unit_Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unit_Tests.XmlStrings", typeof(XmlStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Mediainfo version=&quot;0.7.67&quot;&gt;
        ///	&lt;File&gt;
        ///		&lt;track type=&quot;General&quot;&gt;
        ///			&lt;Unique_ID&gt;185349421464521665070065006788652863604 (0x8B710006610C53A8968F1EE1ED9C9074)&lt;/Unique_ID&gt;
        ///			&lt;Complete_name&gt;Weiss Survive (10).mkv&lt;/Complete_name&gt;
        ///			&lt;Format&gt;Matroska&lt;/Format&gt;
        ///			&lt;Format_version&gt;Version 1&lt;/Format_version&gt;
        ///			&lt;File_size&gt;30.5 MiB&lt;/File_size&gt;
        ///			&lt;Duration&gt;2mn 31s&lt;/Duration&gt;
        ///			&lt;Overall_bit_rate_mode&gt;Variable&lt;/Overall_bit_rate_mode&gt;
        ///			&lt;Overall_bit_rate&gt;1 686 Kbps&lt;/Overall_bit_rate&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidMediaInfoXml {
            get {
                return ResourceManager.GetString("ValidMediaInfoXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file://path/to/file.mkv.
        /// </summary>
        internal static string ValidXmlExpectedPath1 {
            get {
                return ResourceManager.GetString("ValidXmlExpectedPath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file://path/to/file2.mkv.
        /// </summary>
        internal static string ValidXmlExpectedPath2 {
            get {
                return ResourceManager.GetString("ValidXmlExpectedPath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;MediaInformationServicesRequest xmlns=&quot;http://nlogneg.com&quot;&gt;
        ///	&lt;Files&gt;
        ///		&lt;File&gt;
        ///			&lt;Path&gt;file://path/to/file.mkv&lt;/Path&gt;
        ///		&lt;/File&gt;
        ///		&lt;File&gt;
        ///			&lt;Path&gt;file://path/to/file2.mkv&lt;/Path&gt;
        ///		&lt;/File&gt;
        ///	&lt;/Files&gt;
        ///&lt;/MediaInformationServicesRequest&gt;.
        /// </summary>
        internal static string ValidXmlRequest {
            get {
                return ResourceManager.GetString("ValidXmlRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;MediaInformationServicesResponse xmlns=&quot;http://nlogneg.com&quot;&gt;
        ///	&lt;Files&gt;
        ///		&lt;File&gt;
        ///			&lt;MediaInfo&gt;
        ///				&lt;AudioTracks&gt;
        ///					&lt;AudioTrack&gt;
        ///						&lt;Id&gt;2&lt;/Id&gt;
        ///						&lt;Format&gt;Vorbis&lt;/Format&gt;
        ///						&lt;Channels&gt;2&lt;/Channels&gt;
        ///						&lt;Language&gt;Japanese&lt;/Language&gt;
        ///					&lt;/AudioTrack&gt;
        ///				&lt;/AudioTracks&gt;
        ///				&lt;SubtitleTracks&gt;
        ///					&lt;SubtitleTrack&gt;
        ///						&lt;Id&gt;3&lt;/Id&gt;
        ///						&lt;Format&gt;ASS&lt;/Format&gt;
        ///						&lt;Language&gt;English&lt;/Language&gt;
        ///					&lt;/SubtitleTrack&gt;
        ///				&lt;/SubtitleTracks&gt;
        ///				&lt;VideoTracks&gt;
        ///					&lt;Vid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidXmlResponse {
            get {
                return ResourceManager.GetString("ValidXmlResponse", resourceCulture);
            }
        }
    }
}
